services:
  # Backend API service
  - type: web
    name: defi-wallet-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: ENCRYPTION_IV
        sync: false
      - key: SECRET_JWT
        sync: false
      - key: EMAIL_SERVICE
        sync: false
      - key: EMAIL
        sync: false
      - key: EMAIL_PWD
        sync: false
      - key: COINMARKET_APIKEY
        sync: false

  # Frontend static site
  - type: web
    name: defi-wallet-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_FIREBASE_API_KEY
        sync: false
      - key: REACT_APP_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: REACT_APP_FIREBASE_PROJECT_ID
        sync: false
      - key: REACT_APP_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: REACT_APP_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: REACT_APP_FIREBASE_APP_ID
        sync: false
      - key: REACT_APP_FIREBASE_MEASUREMENT_ID
        sync: false 